on:
  push: {}
  workflow_dispatch: {}
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Extract some files
      run: unzip -qq './internalportal-report.zip' -d ./internalportal-report
  

