on:
  push: {}
  workflow_dispatch: {}
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Extract some files
      run: |
        filename=internalportal-report.zip
        unzip *.zip
        rm *.zip
        mv $filename temp
        mv temp/out/* .
        rm -r temp
        git config --local user.email "github-actions@users.noreply.github.com"
        git config --local user.name "github-actions"
        git add .
        git commit -m "unzip"
        git push origin main  
  

